packages:
  - apps/*
  - packages/*
  - tools/*
  - examples/*

catalogMode: manual
cleanupUnusedCatalogs: true

catalog:
  "@types/node": ^24
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: ^4.1.9
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  protobufjs: false
  yarn: false
minimumReleaseAgeExclude:
  - "@commerce-klaus/sfcc-module-resolver@1.1.0"
