import {
  type ResolvedStepTypeDefinition,
  type StepTypeParameterDefinition,
  findResolvedStepTypeDefinitions,
} from "@commerce-klaus/sfcc-module-resolver"
import {
  existsSync as nodeExistsSync,
  mkdirSync as nodeMkdirSync,
  writeFileSync as nodeWriteFileSync,
} from "node:fs"
import path from "node:path"

import { inferCartridgeOrder, resolveGeneratedJobStepTypesPath } from "./shared.ts"

export interface GenerateJobStepTypesOptions {
  workspaceRoot: string
  cartridgesDir?: string
  existsSync?: (filePath: string) => boolean
  mkdirSync?: (dirPath: string, options: { recursive: boolean }) => void
  writeFileSync?: (filePath: string, content: string, encoding: BufferEncoding) => void
}

export interface GenerateJobStepTypesResult {
  declarationsCount: number
  outputFilePath: string
  sourceFiles: string[]
  written: boolean
}

export function generateJobStepTypes(
  options: GenerateJobStepTypesOptions,
): GenerateJobStepTypesResult {
  const existsSync = options.existsSync ?? nodeExistsSync
  const mkdirSync = options.mkdirSync ?? nodeMkdirSync
  const writeFileSync = options.writeFileSync ?? nodeWriteFileSync
  const cartridgesDir = options.cartridgesDir ?? path.join(options.workspaceRoot, "cartridges")
  const outputFilePath = resolveGeneratedJobStepTypesPath(options.workspaceRoot)

  if (!existsSync(cartridgesDir)) {
    return { declarationsCount: 0, outputFilePath, sourceFiles: [], written: false }
  }

  const cartridgeRoots = inferCartridgeOrder(cartridgesDir)
  const definitions = findResolvedStepTypeDefinitions(cartridgeRoots)
  const sourceFiles = cartridgeRoots
    .map((cartridgeRoot) => path.join(cartridgeRoot, "steptypes.json"))
    .filter((filePath) => existsSync(filePath))

  if (definitions.length === 0) {
    return { declarationsCount: 0, outputFilePath, sourceFiles, written: false }
  }

  mkdirSync(path.dirname(outputFilePath), { recursive: true })
  writeFileSync(outputFilePath, renderJobStepTypes(definitions), "utf8")

  return {
    declarationsCount: definitions.length,
    outputFilePath,
    sourceFiles,
    written: true,
  }
}

function renderJobStepTypes(definitions: ResolvedStepTypeDefinition[]): string {
  return [
    "/* Auto-generated by sfcc-ts-sync-types. Do not edit manually. */",
    'import JobStepExecution = require("dw/job/JobStepExecution")',
    'import Status = require("dw/system/Status")',
    'import List = require("dw/util/List")',
    "",
    "declare global {",
    "  namespace SfccJobSteps {",
    "    interface Definitions {",
    ...definitions.flatMap(renderDefinition),
    "    }",
    "  }",
    "}",
    "",
    "export {}",
    "",
  ].join("\n")
}

function renderDefinition(definition: ResolvedStepTypeDefinition): string[] {
  const runtimeParameters = renderParameters(definition.parameters, false)
  const inputParameters = renderParameters(definition.parameters, true)
  const statusCodes = [
    ...new Set([
      "OK",
      "ERROR",
      ...(definition.kind === "script-module-step" ? definition.statusCodes : []),
    ]),
  ]
    .map((statusCode) => JSON.stringify(statusCode))
    .join(" | ")

  return [
    `      ${JSON.stringify(definition.typeId)}: {`,
    `        Input: ${inputParameters}`,
    `        Parameters: ${runtimeParameters}`,
    `        StatusCode: ${statusCodes}`,
    "        Functions: {",
    ...renderFunctions(definition, runtimeParameters),
    "        }",
    "      }",
  ]
}

function renderParameters(parameters: StepTypeParameterDefinition[], forInput: boolean): string {
  if (parameters.length === 0) {
    return "Record<string, never>"
  }

  const members = parameters.map((parameter) => {
    const optional = forInput
      ? !parameter.required || parameter.defaultValue !== undefined
      : !parameter.required && parameter.defaultValue === undefined
    return `${JSON.stringify(parameter.name)}${optional ? "?" : ""}: ${renderParameterType(parameter)}`
  })
  return `{ ${members.join("; ")} }`
}

function renderParameterType(parameter: StepTypeParameterDefinition): string {
  if (parameter.enumValues && parameter.enumValues.length > 0) {
    return parameter.enumValues.map((value) => JSON.stringify(value)).join(" | ")
  }
  if (parameter.targetType === "long") {
    return "number"
  }
  if (
    parameter.targetType === "date" ||
    parameter.type === "date-string" ||
    parameter.type === "datetime-string" ||
    parameter.type === "time-string"
  ) {
    return "Date"
  }

  switch (parameter.type) {
    case "boolean":
      return "boolean"
    case "double":
    case "long":
      return "number"
    case "string":
      return "string"
    default:
      return "unknown"
  }
}

function renderFunctions(definition: ResolvedStepTypeDefinition, parametersType: string): string[] {
  const standardArguments = `parameters: ${parametersType}, stepExecution: JobStepExecution`
  if (definition.kind === "script-module-step") {
    return [
      `          ${JSON.stringify(definition.functionName)}: (${standardArguments}) => Status | void`,
    ]
  }

  const signatures: Partial<Record<keyof typeof definition.functions, string>> = {
    afterChunk: `(${standardArguments}) => void`,
    afterStep: `(success: boolean, ${standardArguments}) => Status | void`,
    beforeChunk: `(${standardArguments}) => void`,
    beforeStep: `(${standardArguments}) => void`,
    getTotalCount: `(${standardArguments}) => number`,
    process: `(item: unknown, ${standardArguments}) => unknown | undefined`,
    read: `(${standardArguments}) => unknown | undefined`,
    write: `(items: List<unknown>, ${standardArguments}) => void`,
  }

  return Object.entries(definition.functions).map(
    ([name, functionName]) =>
      `          ${JSON.stringify(functionName)}: ${signatures[name as keyof typeof signatures]}`,
  )
}
