import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import { renderProjectGraphMermaid } from "../../packages/b2c-plugin/src/output.ts"
import { createSfccProjectGraph } from "../../packages/sfcc-module-resolver/src/project-graph.ts"

const repositoryRoot = fileURLToPath(new URL("../..", import.meta.url))
const cartridgesDirectory = path.join(repositoryRoot, "examples/eslint-typescript-sfcc/cartridges")
const outputPath = path.join(repositoryRoot, "docs/_partials/project-graph.generated.md")
const generatorPath = fileURLToPath(import.meta.url)

export function generateProjectGraphDocumentation(): void {
  const graph = createSfccProjectGraph({
    cartridgesDir: cartridgesDirectory,
    cartridgePath: ["app_custom", "app_example"],
  })
  const mermaid = renderProjectGraphMermaid(graph)
  const encodedDefinition = Buffer.from(mermaid, "utf8").toString("base64")
  const content = [
    "<!-- Generated by docs/.vitepress/generate-project-graph.ts. Do not edit. -->",
    "",
    `<ProjectGraphDiagram encoded-definition="${encodedDefinition}" />`,
    "",
  ].join("\n")

  if (!fs.existsSync(outputPath) || fs.readFileSync(outputPath, "utf8") !== content) {
    fs.writeFileSync(outputPath, content, "utf8")
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === generatorPath) {
  generateProjectGraphDocumentation()
}
