name: Release Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
          run-install: true

      - name: Test npm publish eslint-config-sfcc
        run: |
          set -euxo pipefail
          cd packages/eslint-config-sfcc
          npm publish --access public --provenance --registry=https://registry.npmjs.org
        env:
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org
          NPM_CONFIG_PROVENANCE: true
          NPM_CONFIG_LOGLEVEL: silly
          NPM_CONFIG_FOREGROUND_SCRIPTS: true
          NPM_CONFIG_TIMING: true
      - name: Create release PR or publish
        uses: changesets/action@v1
        with:
          version: vp run version-packages
          publish: vp run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: "*"
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
          NPM_CONFIG_PROVENANCE: true
          NPM_CONFIG_LOGLEVEL: verbose
